# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerngeistGateway < Formula
  desc "Self-hosted backend service for ACP-compatible agents"
  homepage "https://github.com/arafatamim/ferngeist-acp-gateway"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.2/ferngeist-gateway_0.11.2_darwin_amd64_brew.tar.gz"
      sha256 "be9526168866397d82a7d5bd711b3f20d657abb912bd6cf70c29de4d1cda351a"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.2/ferngeist-gateway_0.11.2_darwin_arm64_brew.tar.gz"
      sha256 "de648c807c9e603256580442f6ab60130a9c9986920a0ad133f0b5a470af2328"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.2/ferngeist-gateway_0.11.2_linux_amd64_brew.tar.gz"
      sha256 "7ef9581270e5b3dc513880309d52f715daeaaa404f89db1bc582d147e52ddf4f"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.2/ferngeist-gateway_0.11.2_linux_arm64_brew.tar.gz"
      sha256 "e31c2ed3f4a0e058774a1e7632a5ea4bb138e89e7eb95ee9c7844593848633aa"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  def post_install
    system "ferngeist-gateway", "daemon", "install", "--lan"
    # Silence the periodic update-available notification: brew-managed
    # installs update via `brew upgrade`, never self-update. Mirror
    # packaging/postinstall.sh's env append (runs as the invoking user,
    # so the env file is user-writable). Wrapped so a path/parse hiccup
    # never fails the formula install (post_install failures abort).
    begin
      linux_env = File.expand_path("~/.local/share/ferngeist-gateway/config/daemon.env")
      mac_env = File.expand_path("~/Library/Application Support/Ferngeist Gateway/config/daemon.plist.env")
      env = File.file?(linux_env) ? linux_env : mac_env
      if File.file?(env)
        content = File.read(env)
        unless content.include?("FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=")
          File.open(env, "a") { |f| f.puts "FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=0" }
        end
      end
    rescue StandardError
      nil
    end
  end
end
