# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerngeistGateway < Formula
  desc "Self-hosted backend service for ACP-compatible agents"
  homepage "https://github.com/arafatamim/ferngeist-acp-gateway"
  version "0.11.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.3/ferngeist-gateway_0.11.3_darwin_amd64_brew.tar.gz"
      sha256 "145d44de37f85789e813fccbe2ab14ca2be2b25afa6e5a48ab982003a46c42f0"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.3/ferngeist-gateway_0.11.3_darwin_arm64_brew.tar.gz"
      sha256 "b969aea39b93f32f71372eadd39a144c43ac15f671fd82851431a6971bb6233a"

      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.3/ferngeist-gateway_0.11.3_linux_amd64_brew.tar.gz"
      sha256 "0ba03598a2dca2f71b7ee950e6e7e2c349937ac279affb10033d8a11e7b08945"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafatamim/ferngeist-acp-gateway/releases/download/v0.11.3/ferngeist-gateway_0.11.3_linux_arm64_brew.tar.gz"
      sha256 "02128ba10fefd5923a923c6fb9e769d4dc5d2a41ee474eeac316226bfc885f52"
      define_method(:install) do
        bin.install "ferngeist-gateway"
      end
    end
  end

  def post_install
    system "ferngeist-gateway", "daemon", "install", "--lan"
    # Silence the periodic update-available notification: brew-managed
    # installs update via `brew upgrade`, never self-update. Mirror
    # packaging/postinstall.sh's env append (runs as the invoking user,
    # so the env file is user-writable). Wrapped so a path/parse hiccup
    # never fails the formula install (post_install failures abort).
    begin
      linux_env = File.expand_path("~/.local/share/ferngeist-gateway/config/daemon.env")
      mac_env = File.expand_path("~/Library/Application Support/Ferngeist Gateway/config/daemon.plist.env")
      env = File.file?(linux_env) ? linux_env : mac_env
      if File.file?(env)
        content = File.read(env)
        unless content.include?("FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=")
          File.open(env, "a") { |f| f.puts "FERNGEIST_GATEWAY_UPDATE_CHECK_ENABLED=0" }
        end
      end
    rescue StandardError
      nil
    end
  end
end
